[2025-01-01T03:40:37.002+0000] {processor.py:186} INFO - Started process (PID=381) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:40:37.005+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:40:37.013+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:40:37.006+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:40:37.225+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:40:37.133+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 17
    start_date=datetime(2024, 12 31),
                              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-01T03:40:37.228+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:40:40.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 3.747 seconds
[2025-01-01T03:40:51.043+0000] {processor.py:186} INFO - Started process (PID=390) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:40:51.044+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:40:51.045+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:40:51.045+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:40:51.102+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:40:51.052+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 17
    start_date=datetime(2024, 12 31),
                              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-01T03:40:51.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:40:51.256+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.217 seconds
[2025-01-01T03:40:52.143+0000] {processor.py:186} INFO - Started process (PID=391) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:40:52.144+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:40:52.145+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:40:52.145+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:40:52.154+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:40:52.153+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 17
    start_date=datetime(2024, 12 31),
                              ^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-01T03:40:52.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:40:52.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.028 seconds
[2025-01-01T03:41:01.290+0000] {processor.py:186} INFO - Started process (PID=392) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:01.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:41:01.292+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:01.291+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:01.316+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:01.313+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 21, in <module>
    task1 = Bash
            ^^^^
NameError: name 'Bash' is not defined. Did you mean: 'hash'?
[2025-01-01T03:41:01.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:01.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.043 seconds
[2025-01-01T03:41:06.353+0000] {processor.py:186} INFO - Started process (PID=393) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:06.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:41:06.354+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:06.354+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:06.370+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:06.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 21, in <module>
    task1 = BashOPe
            ^^^^^^^
NameError: name 'BashOPe' is not defined
[2025-01-01T03:41:06.372+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:06.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.036 seconds
[2025-01-01T03:41:10.465+0000] {processor.py:186} INFO - Started process (PID=396) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:10.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:41:10.466+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:10.466+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:10.493+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:10.486+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 21, in <module>
    task1 = BashOperator(
            ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2025-01-01T03:41:10.494+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:10.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.044 seconds
[2025-01-01T03:41:18.603+0000] {processor.py:186} INFO - Started process (PID=405) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:18.605+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:41:18.608+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:18.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:18.653+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:18.641+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 21, in <module>
    task1 = BashOperator(
            ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2025-01-01T03:41:18.655+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:18.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.126 seconds
[2025-01-01T03:41:21.723+0000] {processor.py:186} INFO - Started process (PID=406) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:21.724+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:41:21.725+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:21.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:21.751+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:21.748+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 21, in <module>
    task1 = BashOperator(
            ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2025-01-01T03:41:21.752+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:21.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.050 seconds
[2025-01-01T03:41:23.823+0000] {processor.py:186} INFO - Started process (PID=407) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:23.824+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:41:23.825+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:23.825+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:23.840+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:23.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 21, in <module>
    task1 = BashOperator(
            ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2025-01-01T03:41:23.841+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:23.852+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.033 seconds
[2025-01-01T03:41:29.945+0000] {processor.py:186} INFO - Started process (PID=408) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:29.946+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:41:29.947+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:29.947+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:29.964+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:29.960+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 21, in <module>
    task1 = BashOperator(
            ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2025-01-01T03:41:29.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:29.976+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.035 seconds
[2025-01-01T03:41:42.169+0000] {processor.py:186} INFO - Started process (PID=411) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:42.170+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:41:42.171+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:42.171+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:42.186+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:42.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 21, in <module>
    task1 = BashOperator(
            ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2025-01-01T03:41:42.189+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:42.202+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.037 seconds
[2025-01-01T03:41:49.419+0000] {processor.py:186} INFO - Started process (PID=420) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:49.419+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:41:49.420+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:49.420+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:49.430+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:49.428+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 22
    task_id='my_name'
            ^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-01T03:41:49.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:49.446+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.032 seconds
[2025-01-01T03:41:54.610+0000] {processor.py:186} INFO - Started process (PID=421) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:54.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:41:54.614+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:54.613+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:54.636+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:54.634+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 22
    task_id='my_name'
            ^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-01T03:41:54.637+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:54.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.051 seconds
[2025-01-01T03:41:55.633+0000] {processor.py:186} INFO - Started process (PID=422) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:55.634+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:41:55.635+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:55.635+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:55.645+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:41:55.644+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 22
    task_id='my_name'
            ^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-01T03:41:55.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:41:55.659+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.030 seconds
[2025-01-01T03:42:01.725+0000] {processor.py:186} INFO - Started process (PID=423) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:01.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:42:01.727+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:01.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:01.735+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:01.734+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 22
    task_id='my_name'
            ^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-01T03:42:01.736+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:01.747+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.025 seconds
[2025-01-01T03:42:06.794+0000] {processor.py:186} INFO - Started process (PID=424) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:06.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:42:06.795+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:06.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:06.821+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:06.988+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:06.988+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:scheduler_dag_with_cron_exp
[2025-01-01T03:42:06.996+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:06.996+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:scheduler_dag_with_cron_exp
[2025-01-01T03:42:07.000+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:06.999+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:scheduler_dag_with_cron_exp
[2025-01-01T03:42:07.004+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:07.004+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:scheduler_dag_with_cron_exp
[2025-01-01T03:42:07.008+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:07.008+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:scheduler_dag_with_cron_exp
[2025-01-01T03:42:07.012+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:07.011+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:scheduler_dag_with_cron_exp
[2025-01-01T03:42:07.015+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:07.015+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:scheduler_dag_with_cron_exp
[2025-01-01T03:42:07.022+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:07.022+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:42:07.030+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:07.030+0000] {dag.py:3262} INFO - Creating ORM DAG for scheduler_dag_with_cron_exp
[2025-01-01T03:42:07.036+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:07.036+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp to 2024-12-31 00:00:00+00:00, run_after=2025-01-01 00:00:00+00:00
[2025-01-01T03:42:07.048+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.259 seconds
[2025-01-01T03:42:08.858+0000] {processor.py:186} INFO - Started process (PID=425) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:08.859+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:42:08.860+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:08.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:08.886+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:08.896+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:08.896+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:42:08.916+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:08.915+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp to 2024-12-31 00:00:00+00:00, run_after=2025-01-01 00:00:00+00:00
[2025-01-01T03:42:08.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.077 seconds
[2025-01-01T03:42:09.978+0000] {processor.py:186} INFO - Started process (PID=428) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:09.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:42:09.980+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:09.980+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:09.996+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:10.007+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:10.007+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:42:10.023+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:10.023+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp to 2024-12-31 00:00:00+00:00, run_after=2025-01-01 00:00:00+00:00
[2025-01-01T03:42:10.036+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.062 seconds
[2025-01-01T03:42:23.250+0000] {processor.py:186} INFO - Started process (PID=437) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:23.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:42:23.252+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:23.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:23.270+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:23.279+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:23.279+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:42:23.298+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:23.298+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp to 2024-12-31 00:00:00+00:00, run_after=2025-01-01 00:00:00+00:00
[2025-01-01T03:42:23.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.072 seconds
[2025-01-01T03:42:30.382+0000] {processor.py:186} INFO - Started process (PID=438) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:30.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:42:30.387+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:30.385+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:30.410+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:30.419+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:30.418+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:42:30.435+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:30.435+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp to 2024-12-31 00:00:00+00:00, run_after=2025-01-01 00:00:00+00:00
[2025-01-01T03:42:30.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.074 seconds
[2025-01-01T03:42:33.524+0000] {processor.py:186} INFO - Started process (PID=439) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:33.525+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:42:33.526+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:33.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:33.547+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:33.556+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:33.556+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:42:33.573+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:33.573+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp to 2024-12-31 00:00:00+00:00, run_after=2025-01-01 00:00:00+00:00
[2025-01-01T03:42:33.589+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.071 seconds
[2025-01-01T03:42:35.566+0000] {processor.py:186} INFO - Started process (PID=440) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:35.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:42:35.567+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:35.567+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:35.594+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:35.602+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:35.602+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:42:35.617+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:35.617+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp to 2024-12-31 00:00:00+00:00, run_after=2025-01-01 00:00:00+00:00
[2025-01-01T03:42:35.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.071 seconds
[2025-01-01T03:42:49.907+0000] {processor.py:186} INFO - Started process (PID=451) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:49.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:42:49.909+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:49.909+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:49.919+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:50.035+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:50.035+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:42:50.049+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:50.049+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T03:42:50.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.158 seconds
[2025-01-01T03:42:59.075+0000] {processor.py:186} INFO - Started process (PID=452) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:59.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:42:59.077+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:59.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:59.092+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:42:59.100+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:59.100+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:42:59.116+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:42:59.116+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T03:42:59.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.058 seconds
[2025-01-01T03:43:02.143+0000] {processor.py:186} INFO - Started process (PID=453) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:02.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:43:02.148+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:02.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:02.182+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:02.176+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 17
    descr
    ^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-01T03:43:02.183+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:02.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.732 seconds
[2025-01-01T03:43:04.118+0000] {processor.py:186} INFO - Started process (PID=454) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:04.130+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:43:04.138+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:04.130+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:04.209+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:04.196+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 17
    descrip
    ^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-01T03:43:04.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:14.333+0000] {processor.py:211} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 207, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 188, in _handle_dag_file_processing
    result: tuple[int, int, int] = dag_file_processor.process_file(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 928, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 648, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(ParseImportError.filename).all()]
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-01-01T03:43:25.965+0000] {processor.py:186} INFO - Started process (PID=457) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:25.967+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:43:25.968+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:25.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:26.108+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:26.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 17
    description="This is scheduler_dag_with_cron_exp"
                
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-01T03:43:26.109+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:26.185+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.230 seconds
[2025-01-01T03:43:30.265+0000] {processor.py:186} INFO - Started process (PID=466) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:30.266+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:43:30.267+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:30.267+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:30.276+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:30.274+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 17
    description="This is scheduler dag_with_cron_exp"
                
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-01T03:43:30.276+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:30.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.090 seconds
[2025-01-01T03:43:32.305+0000] {processor.py:186} INFO - Started process (PID=467) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:32.306+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:43:32.307+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:32.307+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:32.358+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:32.314+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 17
    description="This is scheduler dag with_cron_exp"
                
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-01T03:43:32.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:32.503+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.202 seconds
[2025-01-01T03:43:33.418+0000] {processor.py:186} INFO - Started process (PID=468) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:33.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:43:33.419+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:33.419+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:33.430+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:33.430+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 17
    description="This is scheduler dag with cron_exp"
                
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-01T03:43:33.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:33.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.086 seconds
[2025-01-01T03:43:35.446+0000] {processor.py:186} INFO - Started process (PID=469) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:35.446+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:43:35.448+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:35.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:35.455+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:35.455+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 17
    description="This is scheduler dag with cron exp"
                
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-01T03:43:35.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:35.469+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.028 seconds
[2025-01-01T03:43:38.499+0000] {processor.py:186} INFO - Started process (PID=470) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:38.499+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:43:38.500+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:38.500+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:38.508+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:38.507+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/scheduler_dag_with_cron_exp.py", line 17
    description="This is scheduler dag with cron expression"
                
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2025-01-01T03:43:38.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:38.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.026 seconds
[2025-01-01T03:43:40.567+0000] {processor.py:186} INFO - Started process (PID=471) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:40.567+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:43:40.568+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:40.568+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:40.590+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:40.801+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:40.801+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:43:40.847+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:40.847+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T03:43:40.868+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.305 seconds
[2025-01-01T03:43:50.720+0000] {processor.py:186} INFO - Started process (PID=472) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:50.721+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:43:50.722+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:50.722+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:50.747+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:50.764+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:50.763+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:43:50.791+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:50.791+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T03:43:50.807+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.092 seconds
[2025-01-01T03:43:59.035+0000] {processor.py:186} INFO - Started process (PID=483) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:59.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:43:59.037+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:59.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:59.097+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:43:59.106+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:59.106+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:43:59.123+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:43:59.123+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T03:43:59.175+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.144 seconds
[2025-01-01T03:44:29.284+0000] {processor.py:186} INFO - Started process (PID=494) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:44:29.285+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:44:29.286+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:44:29.286+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:44:29.299+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:44:29.316+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:44:29.316+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:44:29.334+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:44:29.334+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T03:44:29.346+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.066 seconds
[2025-01-01T03:44:59.941+0000] {processor.py:186} INFO - Started process (PID=505) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:44:59.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:44:59.944+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:44:59.944+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:44:59.963+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:44:59.986+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:44:59.985+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:45:00.003+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:00.003+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T03:45:00.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.078 seconds
[2025-01-01T03:45:08.083+0000] {processor.py:186} INFO - Started process (PID=506) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:45:08.084+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:45:08.085+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:08.085+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:45:08.115+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:08.108+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2025-01-01T03:45:08.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:45:08.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.051 seconds
[2025-01-01T03:45:11.182+0000] {processor.py:186} INFO - Started process (PID=507) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:45:11.182+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:45:11.183+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:11.183+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:45:11.197+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:11.195+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/scheduler_dag_with_cron_exp.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2025-01-01T03:45:11.197+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:45:11.208+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.030 seconds
[2025-01-01T03:45:13.236+0000] {processor.py:186} INFO - Started process (PID=508) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:45:13.236+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:45:13.237+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:13.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:45:13.260+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:45:13.405+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:13.405+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:45:13.421+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:13.421+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T03:45:13.443+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.211 seconds
[2025-01-01T03:45:21.416+0000] {processor.py:186} INFO - Started process (PID=509) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:45:21.417+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:45:21.418+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:21.417+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:45:21.434+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp_v1' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:45:21.503+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:21.503+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:scheduler_dag_with_cron_exp_v1
[2025-01-01T03:45:21.510+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:21.510+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:scheduler_dag_with_cron_exp_v1
[2025-01-01T03:45:21.514+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:21.514+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:scheduler_dag_with_cron_exp_v1
[2025-01-01T03:45:21.520+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:21.520+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:scheduler_dag_with_cron_exp_v1
[2025-01-01T03:45:21.524+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:21.524+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:scheduler_dag_with_cron_exp_v1
[2025-01-01T03:45:21.529+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:21.529+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:scheduler_dag_with_cron_exp_v1
[2025-01-01T03:45:21.533+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:21.533+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:scheduler_dag_with_cron_exp_v1
[2025-01-01T03:45:21.534+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:21.534+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:45:21.542+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:21.542+0000] {dag.py:3262} INFO - Creating ORM DAG for scheduler_dag_with_cron_exp_v1
[2025-01-01T03:45:21.548+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:45:21.548+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp_v1 to 2024-12-31 00:00:00+00:00, run_after=2025-01-01 00:00:00+00:00
[2025-01-01T03:45:21.564+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.152 seconds
[2025-01-01T03:46:57.066+0000] {processor.py:186} INFO - Started process (PID=514) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:46:57.067+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:46:57.073+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:46:57.068+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:46:58.386+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp_v1' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:47:43.631+0000] {processor.py:211} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 207, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 188, in _handle_dag_file_processing
    result: tuple[int, int, int] = dag_file_processor.process_file(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 942, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 982, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 708, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 721, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 686, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/serialized_dag.py", line 160, in write_dag
    if session.scalar(
       ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-01-01T03:48:29.914+0000] {processor.py:186} INFO - Started process (PID=519) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:48:29.915+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:48:29.916+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:48:29.916+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:48:29.934+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp_v1' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:48:30.484+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:48:30.484+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:48:30.500+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:48:30.500+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp_v1 to 2024-12-20 00:00:00+00:00, run_after=2024-12-21 00:00:00+00:00
[2025-01-01T03:48:30.562+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.652 seconds
[2025-01-01T03:48:54.500+0000] {processor.py:186} INFO - Started process (PID=523) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:48:54.500+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T03:48:54.505+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:48:54.501+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:48:54.569+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp_v1' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T03:48:54.583+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:48:54.582+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T03:48:54.608+0000] {logging_mixin.py:190} INFO - [2025-01-01T03:48:54.608+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp_v1 to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T03:48:54.628+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.152 seconds
[2025-01-01T04:08:33.902+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:08:33.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T04:08:33.908+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:08:33.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:08:33.932+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp_v1' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:08:33.985+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:08:33.985+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T04:08:34.021+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:08:34.021+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp_v1 to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T04:08:34.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.162 seconds
[2025-01-01T04:08:44.079+0000] {processor.py:186} INFO - Started process (PID=91) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:08:44.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T04:08:44.094+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:08:44.092+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:08:44.562+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp_v1' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:08:44.701+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:08:44.701+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'scheduler_dag_with_cron_exp_v1', 'Task Id': 'my_name', 'Run Id': 'scheduled__2024-12-23T00:00:00+00:00', 'Hostname': 'b0ef9544b3b5', 'External Executor Id': '504a6adf-680a-45b8-87ab-282e60b2a4e2'}
[2025-01-01T04:08:44.886+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:08:44.886+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=scheduler_dag_with_cron_exp_v1, task_id=my_name, run_id=scheduled__2024-12-23T00:00:00+00:00, execution_date=20241223T000000, start_date=20250101T034841, end_date=20250101T040844
[2025-01-01T04:08:44.952+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:08:44.952+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: scheduler_dag_with_cron_exp_v1.my_name scheduled__2024-12-23T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-01T04:08:45.179+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:08:45.179+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T04:08:45.241+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:08:45.241+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp_v1 to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T04:08:45.261+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 1.203 seconds
[2025-01-01T04:09:16.089+0000] {processor.py:186} INFO - Started process (PID=102) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:09:16.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T04:09:16.113+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:09:16.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:09:16.133+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp_v1' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:09:16.255+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:09:16.255+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T04:09:16.323+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:09:16.322+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp_v1 to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T04:09:16.494+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.420 seconds
[2025-01-01T04:09:46.821+0000] {processor.py:186} INFO - Started process (PID=113) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:09:46.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T04:09:46.826+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:09:46.825+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:09:46.853+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp_v1' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:09:46.952+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:09:46.952+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T04:09:46.974+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:09:46.974+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp_v1 to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T04:09:46.991+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.183 seconds
[2025-01-01T04:10:12.618+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:10:12.619+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T04:10:12.622+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:10:12.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:10:12.653+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp_v1' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:10:16.798+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:10:16.798+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T04:10:16.821+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:10:16.820+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp_v1 to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T04:10:16.851+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 4.242 seconds
[2025-01-01T04:10:24.768+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:10:24.769+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T04:10:24.775+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:10:24.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:10:24.820+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp_v1' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:10:24.840+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:10:24.839+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T04:10:24.873+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:10:24.873+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp_v1 to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T04:10:24.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.139 seconds
[2025-01-01T04:14:09.852+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:14:09.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T04:14:10.123+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:14:09.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:14:58.855+0000] {processor.py:186} INFO - Started process (PID=150) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:14:58.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T04:14:58.858+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:14:58.857+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:14:59.097+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp_v1' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:15:00.860+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:00.860+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T04:15:00.907+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:00.907+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp_v1 to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T04:15:00.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 2.182 seconds
[2025-01-01T04:15:14.048+0000] {processor.py:186} INFO - Started process (PID=159) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:15:14.049+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T04:15:14.050+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:14.050+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:15:14.085+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp_v1' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:15:14.099+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:14.098+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T04:15:14.282+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:14.282+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp_v1 to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T04:15:14.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.255 seconds
[2025-01-01T04:15:38.810+0000] {processor.py:186} INFO - Started process (PID=170) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:15:38.812+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T04:15:38.813+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:38.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:15:38.835+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp_v2' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:15:39.067+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:39.066+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:scheduler_dag_with_cron_exp_v2
[2025-01-01T04:15:39.073+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:39.073+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:scheduler_dag_with_cron_exp_v2
[2025-01-01T04:15:39.077+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:39.077+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:scheduler_dag_with_cron_exp_v2
[2025-01-01T04:15:39.082+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:39.081+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:scheduler_dag_with_cron_exp_v2
[2025-01-01T04:15:39.086+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:39.086+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:scheduler_dag_with_cron_exp_v2
[2025-01-01T04:15:39.090+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:39.090+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:scheduler_dag_with_cron_exp_v2
[2025-01-01T04:15:39.094+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:39.094+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:scheduler_dag_with_cron_exp_v2
[2025-01-01T04:15:39.095+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:39.095+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T04:15:39.102+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:39.101+0000] {dag.py:3262} INFO - Creating ORM DAG for scheduler_dag_with_cron_exp_v2
[2025-01-01T04:15:39.107+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:39.107+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp_v2 to 2024-12-25 00:00:00+00:00, run_after=2024-12-26 00:00:00+00:00
[2025-01-01T04:15:39.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.314 seconds
[2025-01-01T04:15:49.270+0000] {processor.py:186} INFO - Started process (PID=171) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:15:49.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T04:15:49.273+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:49.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:15:49.303+0000] {processor.py:925} INFO - DAG(s) 'scheduler_dag_with_cron_exp_v2' retrieved from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:15:49.314+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:49.314+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-01T04:15:49.522+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:15:49.521+0000] {dag.py:4180} INFO - Setting next_dagrun for scheduler_dag_with_cron_exp_v2 to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-01-01T04:15:49.537+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/scheduler_dag_with_cron_exp.py took 0.273 seconds
[2025-01-01T04:28:45.051+0000] {processor.py:186} INFO - Started process (PID=182) to work on /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:29:25.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/scheduler_dag_with_cron_exp.py for tasks to queue
[2025-01-01T04:31:38.311+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:30:42.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/scheduler_dag_with_cron_exp.py
[2025-01-01T04:46:23.865+0000] {logging_mixin.py:190} INFO - [2025-01-01T04:42:50.893+0000] {timeout.py:68} ERROR - Process timed out, PID: 182
